import { Space_Grotesk } from "next/font/google";
import Head from "next/head";

import GNB from "@/components/GNB";

const grotesk = Space_Grotesk({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={grotesk.style} className="w-full p-10">
        <GNB />
      </main>
    </>
  );
}
